Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,1 +1,30 @@
+pipeline{
+ agent any
+ stages{
+ stage('Build'){
+ steps{
+ sh 'g++ -o task5 task5_code.cpp'
+ build job: 'PES1UG20CS148-1'
+ }
+ }
+ stage('Test'){
+ steps{
+ sh './task5'
+ sh 'exit 1'//error
+
+ }
+ }
+ stage('Deploy'){
+ steps{
+ echo 'Deploying'
+
+ }
+ }
+ }
+ post{
+ failure{
+ echo 'Pipeline failed'
+ }
+ }
+}
 
